/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCs1000pk0GetGmtReservQtyResponse implements Serializable {


    @ColumnAlias("poutGmtRes")
    private List<ProcCs1000pk0GetGmtReservQtyResponsePoutGmtRes> poutGmtRes;

    public List<ProcCs1000pk0GetGmtReservQtyResponsePoutGmtRes> getPoutGmtRes() {
        return this.poutGmtRes;
    }

    public void setPoutGmtRes(List<ProcCs1000pk0GetGmtReservQtyResponsePoutGmtRes> poutGmtRes) {
        this.poutGmtRes = poutGmtRes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCs1000pk0GetGmtReservQtyResponse)) return false;
        final ProcCs1000pk0GetGmtReservQtyResponse procCs1000pk0getGmtReservQtyResponse = (ProcCs1000pk0GetGmtReservQtyResponse) o;
        return Objects.equals(getPoutGmtRes(), procCs1000pk0getGmtReservQtyResponse.getPoutGmtRes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutGmtRes());
    }
}