/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCs1000pk0Cs411qryReservationResponsePoutreservation implements Serializable {


    @ColumnAlias("TORDNUM")
    private String tordnum;

    @ColumnAlias("TGMTSEQ")
    private String tgmtseq;

    @ColumnAlias("W_GMTDES")
    private String wgmtdes;

    @ColumnAlias("TCLRSEQ")
    private Byte tclrseq;

    @ColumnAlias("W_CLRABB")
    private String wclrabb;

    @ColumnAlias("TSZESEQ")
    private Byte tszeseq;

    @ColumnAlias("W_SZEDES")
    private String wszedes;

    @ColumnAlias("TRNQTY")
    private BigInteger trnqty;

    @ColumnAlias("RECDAT")
    private LocalDateTime recdat;

    @ColumnAlias("RECBY")
    private String recby;

    public String getTordnum() {
        return this.tordnum;
    }

    public void setTordnum(String tordnum) {
        this.tordnum = tordnum;
    }

    public String getTgmtseq() {
        return this.tgmtseq;
    }

    public void setTgmtseq(String tgmtseq) {
        this.tgmtseq = tgmtseq;
    }

    public String getWgmtdes() {
        return this.wgmtdes;
    }

    public void setWgmtdes(String wgmtdes) {
        this.wgmtdes = wgmtdes;
    }

    public Byte getTclrseq() {
        return this.tclrseq;
    }

    public void setTclrseq(Byte tclrseq) {
        this.tclrseq = tclrseq;
    }

    public String getWclrabb() {
        return this.wclrabb;
    }

    public void setWclrabb(String wclrabb) {
        this.wclrabb = wclrabb;
    }

    public Byte getTszeseq() {
        return this.tszeseq;
    }

    public void setTszeseq(Byte tszeseq) {
        this.tszeseq = tszeseq;
    }

    public String getWszedes() {
        return this.wszedes;
    }

    public void setWszedes(String wszedes) {
        this.wszedes = wszedes;
    }

    public BigInteger getTrnqty() {
        return this.trnqty;
    }

    public void setTrnqty(BigInteger trnqty) {
        this.trnqty = trnqty;
    }

    public LocalDateTime getRecdat() {
        return this.recdat;
    }

    public void setRecdat(LocalDateTime recdat) {
        this.recdat = recdat;
    }

    public String getRecby() {
        return this.recby;
    }

    public void setRecby(String recby) {
        this.recby = recby;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCs1000pk0Cs411qryReservationResponsePoutreservation)) return false;
        final ProcCs1000pk0Cs411qryReservationResponsePoutreservation procCs1000pk0cs411qryReservationResponsePoutreservation = (ProcCs1000pk0Cs411qryReservationResponsePoutreservation) o;
        return Objects.equals(getTordnum(), procCs1000pk0cs411qryReservationResponsePoutreservation.getTordnum()) &&
                Objects.equals(getTgmtseq(), procCs1000pk0cs411qryReservationResponsePoutreservation.getTgmtseq()) &&
                Objects.equals(getWgmtdes(), procCs1000pk0cs411qryReservationResponsePoutreservation.getWgmtdes()) &&
                Objects.equals(getTclrseq(), procCs1000pk0cs411qryReservationResponsePoutreservation.getTclrseq()) &&
                Objects.equals(getWclrabb(), procCs1000pk0cs411qryReservationResponsePoutreservation.getWclrabb()) &&
                Objects.equals(getTszeseq(), procCs1000pk0cs411qryReservationResponsePoutreservation.getTszeseq()) &&
                Objects.equals(getWszedes(), procCs1000pk0cs411qryReservationResponsePoutreservation.getWszedes()) &&
                Objects.equals(getTrnqty(), procCs1000pk0cs411qryReservationResponsePoutreservation.getTrnqty()) &&
                Objects.equals(getRecdat(), procCs1000pk0cs411qryReservationResponsePoutreservation.getRecdat()) &&
                Objects.equals(getRecby(), procCs1000pk0cs411qryReservationResponsePoutreservation.getRecby());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTordnum(),
                getTgmtseq(),
                getWgmtdes(),
                getTclrseq(),
                getWclrabb(),
                getTszeseq(),
                getWszedes(),
                getTrnqty(),
                getRecdat(),
                getRecby());
    }
}