/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCs1000pk0Cs411qryReservationResponse implements Serializable {


    @ColumnAlias("pOutreservation")
    private List<ProcCs1000pk0Cs411qryReservationResponsePoutreservation> poutreservation;

    public List<ProcCs1000pk0Cs411qryReservationResponsePoutreservation> getPoutreservation() {
        return this.poutreservation;
    }

    public void setPoutreservation(List<ProcCs1000pk0Cs411qryReservationResponsePoutreservation> poutreservation) {
        this.poutreservation = poutreservation;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCs1000pk0Cs411qryReservationResponse)) return false;
        final ProcCs1000pk0Cs411qryReservationResponse procCs1000pk0cs411qryReservationResponse = (ProcCs1000pk0Cs411qryReservationResponse) o;
        return Objects.equals(getPoutreservation(), procCs1000pk0cs411qryReservationResponse.getPoutreservation());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutreservation());
    }
}