/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCs1000pk0GetGmtReservQtyResponsePoutGmtRes implements Serializable {


    @ColumnAlias("TRNNUM")
    private String trnnum;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("GMTSEQ")
    private String gmtseq;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("SZESEQ")
    private Byte szeseq;

    @ColumnAlias("TORDNUM")
    private String tordnum;

    @ColumnAlias("TGMTSEQ")
    private String tgmtseq;

    @ColumnAlias("TCLRSEQ")
    private Byte tclrseq;

    @ColumnAlias("TSZESEQ")
    private Byte tszeseq;

    @ColumnAlias("TRNQTY")
    private BigInteger trnqty;

    @ColumnAlias("QTYRET")
    private BigInteger qtyret;

    @ColumnAlias("QTYCAN")
    private BigInteger qtycan;

    @ColumnAlias("LCNCOD")
    private String lcncod;

    @ColumnAlias("RECBY")
    private String recby;

    @ColumnAlias("RECDAT")
    private LocalDateTime recdat;

    @ColumnAlias("TRNSTS")
    private String trnsts;

    @ColumnAlias("W_QTYNOTUSED")
    private BigInteger wqtynotused;

    @ColumnAlias("W_TOTQTY")
    private BigInteger wtotqty;

    @ColumnAlias("W_TOTRET")
    private BigInteger wtotret;

    @ColumnAlias("W_QTYCAN")
    private BigInteger wqtycan;

    @ColumnAlias("W_TOT_QTYNOTUSED")
    private BigInteger wtotQtynotused;

    @ColumnAlias("W_GMT")
    private String wgmt;

    @ColumnAlias("W_CLR")
    private String wclr;

    @ColumnAlias("W_SZE")
    private String wsze;

    @ColumnAlias("W_TGMT")
    private String wtgmt;

    @ColumnAlias("W_TCLR")
    private String wtclr;

    @ColumnAlias("W_TSZE")
    private String wtsze;

    public String getTrnnum() {
        return this.trnnum;
    }

    public void setTrnnum(String trnnum) {
        this.trnnum = trnnum;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public Byte getSzeseq() {
        return this.szeseq;
    }

    public void setSzeseq(Byte szeseq) {
        this.szeseq = szeseq;
    }

    public String getTordnum() {
        return this.tordnum;
    }

    public void setTordnum(String tordnum) {
        this.tordnum = tordnum;
    }

    public String getTgmtseq() {
        return this.tgmtseq;
    }

    public void setTgmtseq(String tgmtseq) {
        this.tgmtseq = tgmtseq;
    }

    public Byte getTclrseq() {
        return this.tclrseq;
    }

    public void setTclrseq(Byte tclrseq) {
        this.tclrseq = tclrseq;
    }

    public Byte getTszeseq() {
        return this.tszeseq;
    }

    public void setTszeseq(Byte tszeseq) {
        this.tszeseq = tszeseq;
    }

    public BigInteger getTrnqty() {
        return this.trnqty;
    }

    public void setTrnqty(BigInteger trnqty) {
        this.trnqty = trnqty;
    }

    public BigInteger getQtyret() {
        return this.qtyret;
    }

    public void setQtyret(BigInteger qtyret) {
        this.qtyret = qtyret;
    }

    public BigInteger getQtycan() {
        return this.qtycan;
    }

    public void setQtycan(BigInteger qtycan) {
        this.qtycan = qtycan;
    }

    public String getLcncod() {
        return this.lcncod;
    }

    public void setLcncod(String lcncod) {
        this.lcncod = lcncod;
    }

    public String getRecby() {
        return this.recby;
    }

    public void setRecby(String recby) {
        this.recby = recby;
    }

    public LocalDateTime getRecdat() {
        return this.recdat;
    }

    public void setRecdat(LocalDateTime recdat) {
        this.recdat = recdat;
    }

    public String getTrnsts() {
        return this.trnsts;
    }

    public void setTrnsts(String trnsts) {
        this.trnsts = trnsts;
    }

    public BigInteger getWqtynotused() {
        return this.wqtynotused;
    }

    public void setWqtynotused(BigInteger wqtynotused) {
        this.wqtynotused = wqtynotused;
    }

    public BigInteger getWtotqty() {
        return this.wtotqty;
    }

    public void setWtotqty(BigInteger wtotqty) {
        this.wtotqty = wtotqty;
    }

    public BigInteger getWtotret() {
        return this.wtotret;
    }

    public void setWtotret(BigInteger wtotret) {
        this.wtotret = wtotret;
    }

    public BigInteger getWqtycan() {
        return this.wqtycan;
    }

    public void setWqtycan(BigInteger wqtycan) {
        this.wqtycan = wqtycan;
    }

    public BigInteger getWtotQtynotused() {
        return this.wtotQtynotused;
    }

    public void setWtotQtynotused(BigInteger wtotQtynotused) {
        this.wtotQtynotused = wtotQtynotused;
    }

    public String getWgmt() {
        return this.wgmt;
    }

    public void setWgmt(String wgmt) {
        this.wgmt = wgmt;
    }

    public String getWclr() {
        return this.wclr;
    }

    public void setWclr(String wclr) {
        this.wclr = wclr;
    }

    public String getWsze() {
        return this.wsze;
    }

    public void setWsze(String wsze) {
        this.wsze = wsze;
    }

    public String getWtgmt() {
        return this.wtgmt;
    }

    public void setWtgmt(String wtgmt) {
        this.wtgmt = wtgmt;
    }

    public String getWtclr() {
        return this.wtclr;
    }

    public void setWtclr(String wtclr) {
        this.wtclr = wtclr;
    }

    public String getWtsze() {
        return this.wtsze;
    }

    public void setWtsze(String wtsze) {
        this.wtsze = wtsze;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCs1000pk0GetGmtReservQtyResponsePoutGmtRes)) return false;
        final ProcCs1000pk0GetGmtReservQtyResponsePoutGmtRes procCs1000pk0getGmtReservQtyResponsePoutGmtRes = (ProcCs1000pk0GetGmtReservQtyResponsePoutGmtRes) o;
        return Objects.equals(getTrnnum(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getTrnnum()) &&
                Objects.equals(getOrdnum(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getOrdnum()) &&
                Objects.equals(getGmtseq(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getGmtseq()) &&
                Objects.equals(getClrseq(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getClrseq()) &&
                Objects.equals(getSzeseq(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getSzeseq()) &&
                Objects.equals(getTordnum(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getTordnum()) &&
                Objects.equals(getTgmtseq(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getTgmtseq()) &&
                Objects.equals(getTclrseq(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getTclrseq()) &&
                Objects.equals(getTszeseq(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getTszeseq()) &&
                Objects.equals(getTrnqty(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getTrnqty()) &&
                Objects.equals(getQtyret(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getQtyret()) &&
                Objects.equals(getQtycan(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getQtycan()) &&
                Objects.equals(getLcncod(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getLcncod()) &&
                Objects.equals(getRecby(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getRecby()) &&
                Objects.equals(getRecdat(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getRecdat()) &&
                Objects.equals(getTrnsts(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getTrnsts()) &&
                Objects.equals(getWqtynotused(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWqtynotused()) &&
                Objects.equals(getWtotqty(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWtotqty()) &&
                Objects.equals(getWtotret(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWtotret()) &&
                Objects.equals(getWqtycan(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWqtycan()) &&
                Objects.equals(getWtotQtynotused(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWtotQtynotused()) &&
                Objects.equals(getWgmt(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWgmt()) &&
                Objects.equals(getWclr(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWclr()) &&
                Objects.equals(getWsze(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWsze()) &&
                Objects.equals(getWtgmt(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWtgmt()) &&
                Objects.equals(getWtclr(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWtclr()) &&
                Objects.equals(getWtsze(), procCs1000pk0getGmtReservQtyResponsePoutGmtRes.getWtsze());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTrnnum(),
                getOrdnum(),
                getGmtseq(),
                getClrseq(),
                getSzeseq(),
                getTordnum(),
                getTgmtseq(),
                getTclrseq(),
                getTszeseq(),
                getTrnqty(),
                getQtyret(),
                getQtycan(),
                getLcncod(),
                getRecby(),
                getRecdat(),
                getTrnsts(),
                getWqtynotused(),
                getWtotqty(),
                getWtotret(),
                getWqtycan(),
                getWtotQtynotused(),
                getWgmt(),
                getWclr(),
                getWsze(),
                getWtgmt(),
                getWtclr(),
                getWtsze());
    }
}