/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.mu.cmt.pfs.pfsdb.models.procedure.*;

public interface PfsdbProcedureExecutorService {

    ProcCs1000pk0GetGmtReservQtyResponse executeProcCS1000PK0_GetGmtReservQty(String pprgid, String psourceOrdnum, String pdestOrdnum, String ptrnnum);

    ProcCs1000pk0Cs411qryReservationResponse executeProcCS1000PK0_CS411QryReservation(String pordnum, String pgmtseq, Integer pclrseq, Integer pszeseq);

    ProcCs1000pk0Cs411qryGmtStockResponse executeProcCS1000PK0_CS411QryGmtStock(String pprgid, String pordnum);

}